
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x08u]\xcc"kT\xee\xcc\xd2\x85o:\xee\xf5\xfd'
    
_lr_action_items = {'COLON':([2,],[7,]),'id':([0,3,5,7,9,10,11,12,13,14,16,17,18,19,20,21,22,23,25,26,27,28,],[2,-6,2,-1,-1,-1,-1,-9,-10,-14,-8,-16,-5,2,-7,-1,-1,-1,-11,-12,-13,-15,]),'RBRACE':([3,4,5,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,],[-6,-4,-1,-1,-3,-1,-1,-1,-9,-10,-14,-8,-16,-5,-1,-7,-1,-1,-1,28,-11,-12,-13,-15,]),'BIGLIST':([0,3,5,7,9,10,11,12,13,14,16,17,18,19,20,21,22,23,25,26,27,28,],[3,-6,3,-1,-1,-1,-1,-9,-10,-14,-8,-16,-5,3,-7,-1,-1,-1,-11,-12,-13,-15,]),'LBRACE':([7,9,10,11,12,13,14,16,20,21,22,23,25,26,27,],[-1,-1,19,-1,-9,-10,-14,-8,-7,-1,-1,-1,-11,-12,-13,]),'string':([7,15,],[11,21,]),'specialkeyword':([7,15,],[12,23,]),'$end':([0,1,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,20,21,22,23,25,26,27,28,],[-1,-2,-6,-4,-1,0,-1,-3,-1,-1,-1,-9,-10,-14,-8,-16,-5,-7,-1,-1,-1,-11,-12,-13,-15,]),'COMMA':([9,11,21,22,23,],[15,15,15,15,15,]),'num':([7,15,],[9,22,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'DefList':([0,5,19,],[1,8,24,]),'epsilon':([0,5,7,9,10,11,19,21,22,23,],[4,4,13,14,17,14,4,14,14,14,]),'OptionalThings':([7,],[10,]),'OptionalBraceBlock':([10,],[18,]),'Definition':([0,5,19,],[5,5,5,]),'S':([0,],[6,]),'OptionalThings2':([9,11,21,22,23,],[16,20,25,26,27,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',75),
  ('S -> DefList','S',1,'p_S','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',84),
  ('DefList -> Definition DefList','DefList',2,'p_DefList','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',88),
  ('DefList -> epsilon','DefList',1,'p_DefList','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',89),
  ('Definition -> id COLON OptionalThings OptionalBraceBlock','Definition',4,'p_Definition','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',102),
  ('Definition -> BIGLIST','Definition',1,'p_Definition2','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',112),
  ('OptionalThings -> string OptionalThings2','OptionalThings',2,'p_OptionalThings','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',122),
  ('OptionalThings -> num OptionalThings2','OptionalThings',2,'p_OptionalThings','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',123),
  ('OptionalThings -> specialkeyword','OptionalThings',1,'p_OptionalThings','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',124),
  ('OptionalThings -> epsilon','OptionalThings',1,'p_OptionalThings','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',125),
  ('OptionalThings2 -> COMMA string OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',134),
  ('OptionalThings2 -> COMMA num OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',135),
  ('OptionalThings2 -> COMMA specialkeyword OptionalThings2','OptionalThings2',3,'p_OptionalThings2','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',136),
  ('OptionalThings2 -> epsilon','OptionalThings2',1,'p_OptionalThings2','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',137),
  ('OptionalBraceBlock -> LBRACE DefList RBRACE','OptionalBraceBlock',3,'p_OptionalBraceBlock','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',146),
  ('OptionalBraceBlock -> epsilon','OptionalBraceBlock',1,'p_OptionalBraceBlock','C:\\Users\\Christian\\Documents\\node\\fbx2obj\\parsefbx.py',147),
]
